trigger:
  branches:
    include:
      - master  # Change this to your main branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install -r requirements.txt
    pytest tests/test_selenium.py
  displayName: 'Run Selenium Tests'
